# Generated by Django 5.2.4 on 2025-07-27 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('network_id', models.IntegerField()),
                ('maker_asset', models.CharField(max_length=42)),
                ('taker_asset', models.CharField(max_length=42)),
                ('making_amount', models.CharField(max_length=78)),
                ('taking_amount', models.CharField(max_length=78)),
                ('maker', models.CharField(db_index=True, max_length=42)),
                ('salt', models.CharField(blank=True, max_length=78, null=True)),
                ('receiver', models.CharField(blank=True, max_length=42, null=True)),
                ('maker_traits', models.CharField(max_length=78)),
                ('extension', models.TextField(blank=True, null=True)),
                ('signature', models.CharField(max_length=132)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_amount', models.CharField(default='0', max_length=78)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['maker', 'status'], name='orderbook_l_maker_e23b02_idx'), models.Index(fields=['maker_asset', 'taker_asset'], name='orderbook_l_maker_a_18ace6_idx'), models.Index(fields=['status', 'created_at'], name='orderbook_l_status_601d47_idx')],
            },
        ),
    ]
