# Generated by Django 5.2.4 on 2025-08-01 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_asset_suffix', models.TextField()),
                ('taker_asset_suffix', models.TextField()),
                ('making_amount_data', models.TextField()),
                ('taking_amount_data', models.TextField()),
                ('predicate', models.TextField()),
                ('maker_permit', models.TextField()),
                ('pre_interaction', models.TextField()),
                ('post_interaction', models.TextField()),
                ('custom_data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='limitorder',
            name='extension',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orderbook.extension'),
        ),
    ]
